# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_login_server', '0004_auto_20170415_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencypersonnel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='location'),
        ),
    ]
