# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_login_server', '0005_auto_20170415_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypersonnel',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
