# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_arbitration_center', '0002_emergency_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='user_adhaar_number',
            field=models.CharField(max_length=12),
        ),
    ]
