# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0003_auto_20170408_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='adhaar_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
