# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 15:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPersonnel',
            fields=[
                ('personnel_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('adhaar_number', models.CharField(max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_number', models.BigIntegerField()),
                ('car_number', models.CharField(max_length=255)),
                ('responder_type', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
