# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_login_server', '0003_auto_20170414_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypersonnel',
            name='device_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='emergencypersonnel',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
