# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency_type', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_server.User')),
            ],
        ),
    ]
