# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_adhaar_number', models.CharField(max_length=12, unique=True)),
                ('emergency_responder_id', models.CharField(blank=True, max_length=255)),
                ('emergency_type', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
