# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_arbitration_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='user',
        ),
        migrations.AddField(
            model_name='emergency',
            name='emergency_responder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emergency',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergency',
            name='user_adhaar_number',
            field=models.CharField(default=123456789011L, max_length=12, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
