# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0002_auto_20170413_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
