# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_server', '0003_auto_20170415_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
